/// ============================================================================
/// Copyright (C) 2023 Pavol Federl (pfederl@ucalgary.ca)
/// All Rights Reserved. Do not distribute this file.
/// ============================================================================
/// DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

#include <cinttypes>
#include <vector>

std::vector<int64_t>
detect_primes(const std::vector<int64_t> & nums, int n_threads);
