/// =========================================================================
/// Copyright (C) 2024 Jonathan Hudson (jwhudson@ucalgary.ca)
/// All Rights Reserved. Do not distribute this file.
/// =========================================================================
/// DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

#include <unistd.h>
#include <stdio.h>
#include <stdio.h>
#include <ctype.h>
#include <string>
#include <vector>

// split string p_line into a vector of strings (words)
// the delimiters are 1 or more whitespaces
std::vector<std::string>
split(const std::string &p_line)
{
  auto line = p_line + " ";
  bool in_str = false;
  std::string curr_word = "";
  std::vector<std::string> res;
  for (auto c : line)
  {
    if (isspace(c))
    {
      if (in_str)
        res.push_back(curr_word);
      in_str = false;
      curr_word = "";
    }
    else
    {
      curr_word.push_back(c);
      in_str = true;
    }
  }
  return res;
}

// global variable used in stdin_readline()
unsigned char buffer;

// reads in a line from STDIN
// reads until \n or EOF and result includes \n if present
// returns empty string on EOF
std::string
stdin_readline()
{
  std::string result;
  while (1 == read(STDIN_FILENO, &buffer, 1))
  {
    result.push_back(buffer);
    if (buffer == '\n')
      break;
  }
  return result;
}

// returns true if a word is stutter
// stutter is a string that reads the same twice in a row
//    after converting all characters to lower case
bool is_stutter(const std::string &s)
{
  if (s.size() % 2 != 0)
    return false;
  for (size_t i = 0; i < s.size() / 2; i++)
    if (tolower(s[i]) != tolower(s[i + s.size() / 2]))
      return false;
  return true;
}

// Returns the longest stutter on standard input.
// In case of ties for length, returns the first stutter found.
//
// Algorithm:
// Input is broken into lines, each line into words, and each word
// is checked to see if it is stutter, and if it is, whether it
// is longer than the largest stutter encountered so far.
//
// A word is a sequence of characters separated by white space
// white space is whatever isspace() says it is
//    i.e. ' ', '\n', '\r', '\t', '\n', '\f'
std::string
get_longest_stutter()
{
  std::string max_stut;
  while (1)
  {
    std::string line = stdin_readline();
    if (line.size() == 0)
      break;
    auto words = split(line);
    for (auto word : words)
    {
      if (word.size() <= max_stut.size())
        continue;
      if (is_stutter(word))
        max_stut = word;
    }
  }
  return max_stut;
}

int main()
{
  std::string max_stut = get_longest_stutter();
  printf("Longest stutter: %s\n", max_stut.c_str());
  return 0;
}
