#!/bin/env python3

# =========================================================================
# Copyright (C) 2024 Jonathan Hudson (jwhudson@ucalgary.ca)
# All Rights Reserved. Do not distribute this file.
# =========================================================================
# DO NOT EDIT THIS FILE. DO NOT SUBMIT THIS FILE FOR GRADING.

import sys

def main():
    max_stutter = b""
    max_len = -1
    while True:
        line = sys.stdin.buffer.readline()
        if len(line) == 0: break
        words = line.split()
        for word in words:
            if len(word) % 2 == 0:
                half = int(len(word)/2)
                if len(word) <= max_len:
                    continue            
                if word.lower()[0:half] == word.lower()[half:]:
                    max_stutter = word
                    max_len = len(max_stutter)
    sys.stdout.buffer.write(b"Longest stutter: ")
    sys.stdout.buffer.write(max_stutter)
    sys.stdout.buffer.write(b"\n")
main()
